### PR TITLE
add lang prop to all articles based on their origin language - WIP

### PR DESCRIPTION
**Pull request by thekemkid**
Card: https://app.clubhouse.io/condenastinternational/story/11246/update-flyway-demo-api-to-include-language

### CODE REVIEW

**Comment by thekemkid** [comment]
WIP - due to the large number of validator changes, this will require a large amount work. Just adding `lang` broke tests, so to get them green, I bumped the validator, which broke the tests _more_ because `galleries`, so to get them back green, I've started the basic work, but realistically, this will require a relatively large code change, because we never considered galleries their own entities, with their own `self` links previously. 😅

**Comment by srilq** [comment]
@thekemkid Feel free to use validator `v1` here for now to avoid needing to add galleries at this stage.

**Comment by almostagile** [comment]
Please, please, please just update the validator to v1.x. This card is part of an epic to add alternate language support only (not to support standalone galleries). I need this change to test https://github.com/conde-nast-international/flyway-service/pull/81

**Comment by thekemkid** [comment]
Done.

**Pull request merged**
